### PR TITLE
IE fix for session cookies

### PR DESCRIPTION
**Pull request by eliasnaur**
expiry=0 apparently doesn't sit well with IE browsers, so I changed to format to leave out the expiry field completely for session cookies. That seems to work in the browsers I have access to (chrome, firefox, ie).

### CODE REVIEW

**Comment by dound** [comment]
Cool, thanks for the patch!  I'll test it and integrate it as part of the next release.  Thanks Elias!

**Comment by eliasnaur** [comment]
Please pull latest changes - this will fix the case where the django caching layer is active and gae-sessions is used and mimics the functionality of the django builtin sessions. The patch adds a Vary header to the response when the session has been accessed to force browser to take cookies into account when caching.

**Comment by dound** [comment]
Excellent, thanks Elias.  My goal is to integrate and release both of your patches this weekend.  Sorry they've been pending for so long!

**Comment by dound** [comment]
Finally, I've integrated your improvements.  Thanks Elias!

**Pull request merged**
